# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dd260d54953d63b62bde8e94bc4d4af60d15229c637e46c0c96d2b2fcfd85339527af174fc81869600ff6291de1e849c6dcf67ffb75236b7e6cd0e9bd5fea90

test:
  secret_key_base: 295213ec6317d93d06a82506397fb0e6d4e85186a042146c3d26bb79f42ae69d68312018a7df2beed2c4b1df51cd789bea36ab23cbe7f17fb65bd9798872d17f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
